name: Distribute GitHub Actions secrets

on:
  push:
    branches: [main]
    paths:
      - "./secrets"
  workflow_dispatch:

jobs:
  build:
    name: Distribute Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Run github-secrets
        run: |
          docker run --rm -v ${PWD}/secrets:/usr/app/secrets mxcd/github-secrets -p -d secrets -k ${{ secrets.AGE_KEY }}
